const characters = [
    {
        id: 1,
        charName: "Mithandir",
        race: "Elfo",
        charClass: "Mago",
        level: 7,
        gold: 250,
        playerName: "Eugenio",
        isActive: true,
    },
    {
        id: 2,
        charName: "Heos",
        race: "Humano",
        charClass: "Paladín",
        level: 6,
        gold: 450,
        playerName: "Carlos",
        isActive: true,
    },
    {
        id: 3,
        charName: "Melkor",
        race: "Orco",
        charClass: "Mercenario",
        level: 8,
        gold: 1480,
        playerName: "Pablo",
        isActive: false,
    },
    {
        id: 4,
        charName: "Yorim",
        race: "Enano",
        charClass: "Guerrero",
        level: 4,
        gold: 300,
        playerName: "Javier",
        isActive: true,
    },
    {
        id: 5,
        charName: "Sanga",
        race: "Elfo Oscuro",
        charClass: "Ilusionista",
        level: 12,
        gold: 3500,
        playerName: "Juan",
        isActive: true,
    },
    {
        id: 6,
        charName: "Valamarth",
        race: "Humano",
        charClass: "Asesino",
        level: 8,
        gold: 1200,
        playerName: "Pablo",
        isActive: true,
    },
    {
        id: 7,
        charName: "Rauko",
        race: "Orco",
        charClass: "Duelista",
        level: 3,
        gold: 800,
        playerName: "Javier",
        isActive: false,
    },
    {
        id: 8,
        charName: "Ulmi",
        race: "Goblin",
        charClass: "Ladron",
        level: 15,
        gold: 9200,
        playerName: "Eugenio",
        isActive: true,
    },
    {
        id: 9,
        charName: "Shinji",
        race: "Elfo",
        charClass: "Arquero",
        level: 11,
        gold: 7300,
        playerName: "Carlos",
        isActive: false,
    },
    {
        id: 10,
        charName: "Ardumat",
        race: "Humano",
        charClass: "Sanador",
        level: 20,
        gold: 7800,
        playerName: "Juan",
        isActive: true,
    },
];